CREATE TABLE PLANEJAMENTO (
    ID CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    ID_CIDADE INT,
    ID_CATEGORIA INT,
    ATIVIDADE INT,
    TIPO INT,
    DATA_ULT_VISITA DATETIME,
    ANO DATE,
    ZONA TEXT,
    STATUS INT,
    SITUACAO INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);