DROP TABLE IF EXISTS sync_confirm;
CREATE TABLE sync_confirm (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ULTIMO_SINCRONISMO TIMESTAMP NULL,
    ID_USUARIO INT NOT NULL,
    SYNC_TABLE VARCHAR(255) NOT NULL,
    UNIQUE KEY unique_usuario_tabela (ID_USUARIO, SYNC_TABLE)
)
