CREATE TABLE IF NOT EXISTS VISITA (
    ID CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    ID_ENDERECO INTEGER,
    ID_PLANEJAMENTO INTEGER,
    PRIMEIRA_VISITA DATETIME,
    SEGUNDA_VISITA DATETIME,
    TIPO_VISITA TEXT,
    NUMERO_QUARTOS TEXT,
    CONTEM_AMOSTRA BOOL,
    CONTEM_TRATAMENTO BOOL,
    SITUACAO_REFERENCIA INTEGER,
    SITUACAO INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS INSPECAO (
    ID CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    ID_VISITA INTEGER,
    TIPO INTEGER,
    NUMERO_DEPOSITOS INTEGER,
    SITUACAO INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AMOSTRA (
    ID CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    ID_VISITA INTEGER,
    NUMERO_INICIO INTEGER,
    NUMERO_FINAL INTEGER,
    QUANTIDADE INTEGER,
    SITUACAO INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS IMAGEM_AMOSTRA (
    ID CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    ID_AMOSTRA INTEGER,
    NOME TEXT,
    IMAGEM BLOB,
    SITUACAO INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TRATAMENTO (
    ID CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    ID_VISITA INTEGER,
    DEPOSITOS_ELIMINADOS INTEGER,
    IMOVEIS_TRATADOS INTEGER,
    QTD_TRATAMENTO INTEGER,
    TIPO TEXT,
    QTD_CARGA INTEGER,
    SITUACAO INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);