ALTER TABLE VISITA DROP COLUMN ID_ENDERECO;
ALTER TABLE VISITA DROP COLUMN ID_PLANEJAMENTO;
ALTER TABLE INSPECAO DROP COLUMN ID_VISITA;
ALTER TABLE AMOSTRA DROP COLUMN ID_VISITA;
ALTER TABLE IMAGEM_AMOSTRA DROP COLUMN ID_AMOSTRA;
ALTER TABLE TRATAMENTO DROP COLUMN ID_VISITA;

ALTER TABLE VISITA ADD COLUMN ID_ENDERECO CHAR(36);
ALTER TABLE VISITA ADD COLUMN ID_PLANEJAMENTO CHAR(36);
ALTER TABLE INSPECAO ADD COLUMN ID_VISITA CHAR(36);
ALTER TABLE AMOSTRA ADD COLUMN ID_VISITA CHAR(36);
ALTER TABLE IMAGEM_AMOSTRA ADD COLUMN ID_AMOSTRA CHAR(36);
ALTER TABLE TRATAMENTO ADD COLUMN ID_VISITA CHAR(36);