ALTER TABLE visita DROP COLUMN ID_ENDERECO;

ALTER TABLE visita ADD COLUMN CEP VARCHAR(255);
ALTER TABLE visita ADD COLUMN NOME VARCHAR(255);
ALTER TABLE visita ADD COLUMN NUMERO INTEGER;
ALTER TABLE visita ADD COLUMN COMPLEMENTO VARCHAR(255);