CREATE TABLE IMAGEM_PERFIL_USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_data BLOB NOT NULL,
    image_name VARCHAR(255) NOT NULL,
    image_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);